version: 2

jobs:
  build_js:
    docker:
      - image: trzeci/emscripten:sdk-incoming-64bit
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: Update cmake
          command: |
            # https://askubuntu.com/a/865294
            version=3.12
            build=2
            mkdir ~/temp
            cd ~/temp
            wget https://cmake.org/files/v$version/cmake-$version.$build-Linux-x86_64.sh
            cmake --version
            which cmake
            ls -l $(which cmake)
            ls -l /opt/cmake
            mkdir /opt/cmake_new
            sh cmake-$version.$build-Linux-x86_64.sh --prefix=/opt/cmake_new --skip-license
            ln -sf /opt/cmake_new/bin/cmake /usr/local/bin/cmake
            cmake --version
#      - run: python javascript/build_rhino3dm.py
      - run:
          name: Build
          command: |
            emcc --version
            python --version
            python src/build_javascript_lib.py
      - persist_to_workspace:
          root: src/build/artifacts_js
          paths:
            - .
  deploy_js:
    docker:
      - image: circleci/python:2.7-jessie
    environment:
      S3_BASE_URL: s3://files.na.mcneel.com/rhino3dm/js
    steps:
      - attach_workspace:
          at: src/build/artifacts_js
      - run: ls -l src/build/artifacts_js
      - run: python --version
      - run: sudo pip install awscli
        # upload artifacts to s3
      - run: aws s3 cp src/build/artifacts_js $S3_BASE_URL/dujour/$CIRCLE_BUILD_NUM/ --recursive --acl public-read
        # re-upload rhino3dm.wasm with mime-type "application/wasm"
      - run: aws s3 cp src/build/artifacts_js/rhino3dm.wasm $S3_BASE_URL/dujour/$CIRCLE_BUILD_NUM/ --acl public-read --content-type "application/wasm"
        # copy artifacts from dujour/$CIRCLE_BUILD_NUM/ to latest/
      - run:
          name: Copy artifacts to latest/
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              aws s3 cp $S3_BASE_URL/dujour/$CIRCLE_BUILD_NUM/ $S3_BASE_URL/latest/ --recursive --acl public-read
            fi

  build_py2:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python python-dev python-pip uuid uuid-dev cmake clang
      - checkout
      - run: git submodule update --init
      - run: python2 --version
      - run: python2 -m pip install -U pip setuptools
      - run: cmake --version
      - run: python2 setup.py bdist_wheel

  build_py3:
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python3 python3-dev python3-pip uuid uuid-dev cmake clang
      - checkout
      - run: git submodule update --init
      - run: python3 --version
      - run: python3 -m pip install -U pip setuptools
      - run: cmake --version
      - run: python3 setup.py bdist_wheel

  build_py2_mac:
    macos:
      xcode: "10.2.0"
    steps:
      # brew update required to workaround Homebrew/brew#5513
      - run: brew update
      - run: brew install cmake
      - run: cmake --version
      - run: python --version
      - checkout
      - run: git submodule update --init
      - run: python setup.py bdist_wheel

workflows:
  version: 2
  build:
    jobs:
      - build_js
      - deploy_js:
          requires:
            - build_js
      - build_py2
      - build_py3
      - build_py2_mac
