version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build_js:
    docker:
      - image: emscripten/emsdk:2.0.10
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python3 --version && emcc --version && cmake --version
      - run: python3 src/build_javascript.py
      - store_artifacts:
          path: src/build/artifacts_js
          destination: .

  build_py2:
    docker:
      - image: mcneel/rhino3dm-dev:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python2 --version && cmake --version
      - run: python2 setup.py bdist_wheel

  build_py3:
    docker:
      - image: python:3.8-slim-buster
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: apt update && apt install -yy git cmake gcc g++
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version
      - run: python3 setup.py bdist_wheel

  build_py3_mac:
    macos:
      xcode: "11.2.0"
    environment:
            HOMEBREW_NO_AUTO_UPDATE: "1"
    steps:
      - run: brew install cmake
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version
      - run: python3 setup.py bdist_wheel

  build_py3_win:
    executor: win/default
    steps:
      - checkout
      - run: git submodule update --init
      - run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - run: python --version; cmake --version
      - run: python setup.py bdist_wheel

  build_dotnet:
    docker:
      - image: mcneel/rhino3dm-dev:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version && dotnet --version
      - run: python3 script/bootstrap.py -p linux
      - run: python3 script/setup.py -p linux -v
      - run: python3 script/build.py -p linux -v

  build_dotnet_amzn2:
    docker:
      - image: mcneel/rhino3dm-dev-amzn2:latest
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: git submodule update --init
      - run: python3 --version && cmake --version && dotnet --version
      - run: python3 script/bootstrap.py -p linux
      - run: python3 script/setup.py -p linux -v
      - run: python3 script/build.py -p linux -v

workflows:
  version: 2
  build:
    jobs:
      - build_js:
          context:
            - docker-hub-creds
      - build_py2:
          context:
            - docker-hub-creds
      - build_py3:
          context:
            - docker-hub-creds
      - build_py3_mac:
          context:
            - docker-hub-creds
      - build_dotnet:
          context:
            - docker-hub-creds
      - build_dotnet_amzn2:
          context:
            - docker-hub-creds
