name: workflow release tmp
on: [workflow_dispatch]
jobs:

  build_dotnet_macos_tmp:
    name: build dotnet macos tmp
    runs-on: macos-11
    steps:
      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.5'
      #- name: setup dotnet
      #  uses: actions/setup-dotnet@v3
      #  with:
      #    dotnet-version: '7.0.x'
      - name: setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.21.1'
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
      - name: info
        run: python --version && cmake --version && dotnet --version && git --version
      - name: checkout
        uses: actions/checkout@v2
      - name: update submodules
        run: ls && git submodule update --init
      - name: bootstrap dotnet macos
        run: python script/bootstrap.py -p macos
      - name: setup dotnet macos
        run: python script/setup.py -p macos -v
      - name: build dotnet macos
        run: python script/build.py -p macos -v
      - name: list
        run: "ls -R src/build/macos"
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          path: src/build/macos/Release/librhino3dm_native.dylib
          name: rhino3dm.net macos